# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(1126, 826)
        dialog.setStyleSheet("MainForm{\n"
"background-color: #FFFFFF;\n"
"}\n"
"QDialog{\n"
"background-color: #FFFFFF;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.main_layout = QtWidgets.QGroupBox(dialog)
        self.main_layout.setStyleSheet("#main_layout {\n"
"border : 0}")
        self.main_layout.setObjectName("main_layout")
        self.main = QtWidgets.QVBoxLayout(self.main_layout)
        self.main.setObjectName("main")
        self.up = QtWidgets.QGroupBox(self.main_layout)
        self.up.setMaximumSize(QtCore.QSize(16777215, 240))
        self.up.setObjectName("up")
        self.up_layout = QtWidgets.QHBoxLayout(self.up)
        self.up_layout.setObjectName("up_layout")
        self.groupBox = QtWidgets.QGroupBox(self.up)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setStyleSheet("QLabel {\n"
"font: 15pt \"楷体\";\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setStyleSheet("QLabel {\n"
"font: 15pt \"楷体\";\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 5, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {font: 12pt \"楷体\";\n"
"border-radius:4px;\n"
"/*border: 1px solid gray;*/\n"
"/* 边框颜色 */  \n"
"border: 1px solid gray;\n"
"background-color: rgb(224, 213, 255);}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(234, 228, 255);}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid gray;\n"
"border-style:inset;\n"
"/* 使文字有一点移动 */  \n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 3, 10, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 85))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_url = QtWidgets.QWidget()
        self.tab_url.setMinimumSize(QtCore.QSize(0, 60))
        self.tab_url.setMaximumSize(QtCore.QSize(16777215, 85))
        self.tab_url.setObjectName("tab_url")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_url)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_url)
        self.pushButton_6.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_6.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("QPushButton {font: 12pt \"楷体\";\n"
"border-radius:4px;\n"
"/*border: 1px solid gray;*/\n"
"/* 边框颜色 */  \n"
"border: 1px solid gray;\n"
"background-color: rgb(224, 213, 255);}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(234, 228, 255);}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid gray;\n"
"border-style:inset;\n"
"/* 使文字有一点移动 */  \n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_3.addWidget(self.pushButton_6, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_url)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setStyleSheet("QLabel {\n"
"font: 15pt \"楷体\";\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_url)
        self.pushButton_3.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton {font: 12pt \"楷体\";\n"
"border-radius:4px;\n"
"/*border: 1px solid gray;*/\n"
"/* 边框颜色 */  \n"
"border: 1px solid gray;\n"
"background-color: rgb(224, 213, 255);}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(234, 228, 255);}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid gray;\n"
"border-style:inset;\n"
"/* 使文字有一点移动 */  \n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 0, 5, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.tab_url)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"font: 13pt \"楷体\";\n"
"}")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_url)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_7.setStyleSheet("QLabel {\n"
"font: 15pt \"楷体\";\n"
"}")
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 2, 1, 1)
        self.urlPageNumspinBox = QtWidgets.QSpinBox(self.tab_url)
        self.urlPageNumspinBox.setMinimumSize(QtCore.QSize(0, 30))
        self.urlPageNumspinBox.setMaximumSize(QtCore.QSize(50, 30))
        self.urlPageNumspinBox.setStyleSheet("QSpinBox{\n"
"font: 13pt \"楷体\";\n"
"}")
        self.urlPageNumspinBox.setMinimum(1)
        self.urlPageNumspinBox.setObjectName("urlPageNumspinBox")
        self.gridLayout_3.addWidget(self.urlPageNumspinBox, 0, 3, 1, 1)
        self.tabWidget.addTab(self.tab_url, "")
        self.tab_author = QtWidgets.QWidget()
        self.tab_author.setMinimumSize(QtCore.QSize(0, 60))
        self.tab_author.setMaximumSize(QtCore.QSize(16777215, 85))
        self.tab_author.setObjectName("tab_author")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_author)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.tab_author)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_6.setStyleSheet("QLabel {\n"
"font: 15pt \"楷体\";\n"
"}")
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_author)
        self.pushButton_7.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_7.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("QPushButton {font: 12pt \"楷体\";\n"
"border-radius:4px;\n"
"/*border: 1px solid gray;*/\n"
"/* 边框颜色 */  \n"
"border: 1px solid gray;\n"
"background-color: rgb(224, 213, 255);}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(234, 228, 255);}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid gray;\n"
"border-style:inset;\n"
"/* 使文字有一点移动 */  \n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_4.addWidget(self.pushButton_7, 0, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_author)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_8.setStyleSheet("QLabel {\n"
"font: 15pt \"楷体\";\n"
"}")
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 2, 1, 1)
        self.authorLineEdit = QtWidgets.QLineEdit(self.tab_author)
        self.authorLineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.authorLineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.authorLineEdit.setStyleSheet("QLineEdit{\n"
"font: 13pt \"楷体\";\n"
"}")
        self.authorLineEdit.setClearButtonEnabled(True)
        self.authorLineEdit.setObjectName("authorLineEdit")
        self.gridLayout_4.addWidget(self.authorLineEdit, 0, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_author)
        self.pushButton_5.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("QPushButton {font: 12pt \"楷体\";\n"
"border-radius:4px;\n"
"/*border: 1px solid gray;*/\n"
"/* 边框颜色 */  \n"
"border: 1px solid gray;\n"
"background-color: rgb(224, 213, 255);}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(234, 228, 255);}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid gray;\n"
"border-style:inset;\n"
"/* 使文字有一点移动 */  \n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_4.addWidget(self.pushButton_5, 0, 5, 1, 1)
        self.authorPageNumspinBox = QtWidgets.QSpinBox(self.tab_author)
        self.authorPageNumspinBox.setMinimumSize(QtCore.QSize(0, 30))
        self.authorPageNumspinBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.authorPageNumspinBox.setStyleSheet("QSpinBox{\n"
"font: 13pt \"楷体\";\n"
"}")
        self.authorPageNumspinBox.setMinimum(1)
        self.authorPageNumspinBox.setObjectName("authorPageNumspinBox")
        self.gridLayout_4.addWidget(self.authorPageNumspinBox, 0, 3, 1, 1)
        self.tabWidget.addTab(self.tab_author, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 11)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton {font: 12pt \"楷体\";\n"
"border-radius:4px;\n"
"/*border: 1px solid gray;*/\n"
"/* 边框颜色 */  \n"
"border: 1px solid gray;\n"
"background-color: rgb(224, 213, 255);}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(234, 228, 255);}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid gray;\n"
"border-style:inset;\n"
"/* 使文字有一点移动 */  \n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 5, 10, 1, 1)
        self.proxyPathEdit = QtWidgets.QLineEdit(self.groupBox)
        self.proxyPathEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.proxyPathEdit.setStyleSheet("QLineEdit{\n"
"font: 13pt \"楷体\";\n"
"}")
        self.proxyPathEdit.setObjectName("proxyPathEdit")
        self.gridLayout_2.addWidget(self.proxyPathEdit, 3, 4, 1, 1)
        self.isOpenAgentCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.isOpenAgentCheckBox.setMinimumSize(QtCore.QSize(0, 30))
        self.isOpenAgentCheckBox.setStyleSheet("QCheckBox {\n"
"font: 15pt \"楷体\";\n"
"}")
        self.isOpenAgentCheckBox.setChecked(True)
        self.isOpenAgentCheckBox.setObjectName("isOpenAgentCheckBox")
        self.gridLayout_2.addWidget(self.isOpenAgentCheckBox, 3, 5, 1, 1)
        self.savePathEdit = QtWidgets.QLineEdit(self.groupBox)
        self.savePathEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.savePathEdit.setStyleSheet("QLineEdit{\n"
"font: 13pt \"楷体\";\n"
"}")
        self.savePathEdit.setClearButtonEnabled(True)
        self.savePathEdit.setObjectName("savePathEdit")
        self.gridLayout_2.addWidget(self.savePathEdit, 5, 4, 1, 5)
        self.authorCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.authorCheckBox.setMinimumSize(QtCore.QSize(0, 0))
        self.authorCheckBox.setStyleSheet("QCheckBox {\n"
"font: 15pt \"楷体\";\n"
"}")
        self.authorCheckBox.setChecked(True)
        self.authorCheckBox.setAutoRepeat(False)
        self.authorCheckBox.setObjectName("authorCheckBox")
        self.gridLayout_2.addWidget(self.authorCheckBox, 5, 9, 1, 1)
        self.downloadTaskNumSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.downloadTaskNumSpinBox.setMinimumSize(QtCore.QSize(0, 30))
        self.downloadTaskNumSpinBox.setStyleSheet("QSpinBox{\n"
"font: 13pt \"楷体\";\n"
"}")
        self.downloadTaskNumSpinBox.setMinimum(1)
        self.downloadTaskNumSpinBox.setMaximum(100)
        self.downloadTaskNumSpinBox.setObjectName("downloadTaskNumSpinBox")
        self.gridLayout_2.addWidget(self.downloadTaskNumSpinBox, 3, 9, 1, 1)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.passwordLineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.passwordLineEdit.setStyleSheet("QLineEdit{\n"
"font: 13pt \"楷体\";\n"
"}")
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.passwordLineEdit.setClearButtonEnabled(True)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.gridLayout_2.addWidget(self.passwordLineEdit, 6, 9, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setMinimumSize(QtCore.QSize(0, 30))
        self.label_10.setStyleSheet("QLabel {\n"
"font: 15pt \"楷体\";\n"
"}")
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 6, 8, 1, 1)
        self.accountLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.accountLineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.accountLineEdit.setStyleSheet("QLineEdit{\n"
"font: 13pt \"楷体\";\n"
"}")
        self.accountLineEdit.setClearButtonEnabled(True)
        self.accountLineEdit.setObjectName("accountLineEdit")
        self.gridLayout_2.addWidget(self.accountLineEdit, 6, 7, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setStyleSheet("QLabel {\n"
"font: 15pt \"楷体\";\n"
"}")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 6, 1, 1, 1)
        self.cookieEdit = QtWidgets.QLineEdit(self.groupBox)
        self.cookieEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.cookieEdit.setStyleSheet("QLineEdit{\n"
"font: 13pt \"楷体\";\n"
"}")
        self.cookieEdit.setInputMask("")
        self.cookieEdit.setClearButtonEnabled(True)
        self.cookieEdit.setObjectName("cookieEdit")
        self.gridLayout_2.addWidget(self.cookieEdit, 6, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setMinimumSize(QtCore.QSize(0, 30))
        self.label_9.setStyleSheet("QLabel {\n"
"font: 15pt \"楷体\";\n"
"}")
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 6, 5, 1, 1)
        self.loginButton = QtWidgets.QPushButton(self.groupBox)
        self.loginButton.setMinimumSize(QtCore.QSize(0, 30))
        self.loginButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.loginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginButton.setStyleSheet("QPushButton {font: 12pt \"楷体\";\n"
"border-radius:4px;\n"
"/*border: 1px solid gray;*/\n"
"/* 边框颜色 */  \n"
"border: 1px solid gray;\n"
"background-color: rgb(224, 213, 255);}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(234, 228, 255);}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid gray;\n"
"border-style:inset;\n"
"/* 使文字有一点移动 */  \n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"}")
        self.loginButton.setObjectName("loginButton")
        self.gridLayout_2.addWidget(self.loginButton, 6, 10, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setStyleSheet("QLabel {\n"
"font: 15pt \"楷体\";\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 7, 1, 2)
        self.up_layout.addWidget(self.groupBox)
        self.button_box = QtWidgets.QGroupBox(self.up)
        self.button_box.setObjectName("button_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.button_box)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.button_box)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {font: 12pt \"楷体\";\n"
"border-radius:4px;\n"
"/*border: 1px solid gray;*/\n"
"/* 边框颜色 */  \n"
"border: 1px solid gray;\n"
"background-color: rgb(224, 213, 255);}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(234, 228, 255);}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid gray;\n"
"border-style:inset;\n"
"/* 使文字有一点移动 */  \n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_8 = QtWidgets.QPushButton(self.button_box)
        self.pushButton_8.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setStyleSheet("QPushButton {font: 12pt \"楷体\";\n"
"border-radius:4px;\n"
"/*border: 1px solid gray;*/\n"
"/* 边框颜色 */  \n"
"border: 1px solid gray;\n"
"background-color: rgb(224, 213, 255);}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(234, 228, 255);}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid gray;\n"
"border-style:inset;\n"
"/* 使文字有一点移动 */  \n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout.addWidget(self.pushButton_8)
        self.batchDownloadButton = QtWidgets.QPushButton(self.button_box)
        self.batchDownloadButton.setMinimumSize(QtCore.QSize(100, 30))
        self.batchDownloadButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.batchDownloadButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.batchDownloadButton.setStyleSheet("QPushButton {font: 12pt \"楷体\";\n"
"border-radius:4px;\n"
"/*border: 1px solid gray;*/\n"
"/* 边框颜色 */  \n"
"border: 1px solid gray;\n"
"background-color: rgb(224, 213, 255);}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(234, 228, 255);}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid gray;\n"
"border-style:inset;\n"
"/* 使文字有一点移动 */  \n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"}")
        self.batchDownloadButton.setObjectName("batchDownloadButton")
        self.verticalLayout.addWidget(self.batchDownloadButton)
        self.downloadOneButton = QtWidgets.QPushButton(self.button_box)
        self.downloadOneButton.setMinimumSize(QtCore.QSize(100, 30))
        self.downloadOneButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.downloadOneButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.downloadOneButton.setStyleSheet("QPushButton {font: 12pt \"楷体\";\n"
"border-radius:4px;\n"
"/*border: 1px solid gray;*/\n"
"/* 边框颜色 */  \n"
"border: 1px solid gray;\n"
"background-color: rgb(224, 213, 255);}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(234, 228, 255);}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid gray;\n"
"border-style:inset;\n"
"/* 使文字有一点移动 */  \n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"}")
        self.downloadOneButton.setObjectName("downloadOneButton")
        self.verticalLayout.addWidget(self.downloadOneButton)
        self.up_layout.addWidget(self.button_box)
        self.main.addWidget(self.up)
        self.list = QtWidgets.QGroupBox(self.main_layout)
        self.list.setObjectName("list")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.list)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableView = QtWidgets.QTableView(self.list)
        self.tableView.setMinimumSize(QtCore.QSize(0, 500))
        self.tableView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableView.setStyleSheet("QTableView{\n"
"font: 12pt \"楷体\";\n"
"}")
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setShowGrid(True)
        self.tableView.setGridStyle(QtCore.Qt.SolidLine)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setCascadingSectionResizes(True)
        self.tableView.horizontalHeader().setSortIndicatorShown(True)
        self.tableView.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout_2.addWidget(self.tableView)
        self.infoLabel = QtWidgets.QLabel(self.list)
        self.infoLabel.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.infoLabel.setStyleSheet("QLabel {\n"
"font: 12pt \"楷体\";\n"
"}")
        self.infoLabel.setWordWrap(True)
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout_2.addWidget(self.infoLabel)
        self.main.addWidget(self.list)
        self.gridLayout.addWidget(self.main_layout, 0, 0, 1, 1)

        self.retranslateUi(dialog)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(dialog.parsing_btn_click)
        self.pushButton_8.clicked.connect(dialog.check_data_status)
        self.batchDownloadButton.clicked.connect(dialog.batch_download_btn_click)
        self.downloadOneButton.clicked.connect(dialog.single_download_btn_click)
        self.pushButton_5.clicked.connect(dialog.select_his_author_btn_click)
        self.pushButton_7.clicked.connect(dialog.save_author_to_file)
        self.pushButton_6.clicked.connect(dialog.save_url_to_file)
        self.pushButton_3.clicked.connect(dialog.select_his_url_btn_click)
        self.pushButton_2.clicked.connect(dialog.create_author_dir_btn)
        self.pushButton_4.clicked.connect(dialog.select_file_dir_btn)
        self.loginButton.clicked.connect(dialog.login_btn_click)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "页面解析"))
        self.groupBox.setTitle(_translate("dialog", "配置"))
        self.label_2.setText(_translate("dialog", "代理地址"))
        self.label_4.setText(_translate("dialog", "存储位置"))
        self.pushButton_2.setText(_translate("dialog", "获取作者"))
        self.pushButton_6.setText(_translate("dialog", "保存地址"))
        self.label.setText(_translate("dialog", "列表地址"))
        self.pushButton_3.setText(_translate("dialog", "历史地址"))
        self.lineEdit.setToolTip(_translate("dialog", "<html><head/><body><p>请输入带视频列表的url链接</p></body></html>"))
        self.lineEdit.setWhatsThis(_translate("dialog", "<html><head/><body><p>2222</p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("dialog", "此处填入想要解析的视频列表"))
        self.label_7.setText(_translate("dialog", "页数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_url), _translate("dialog", "地址"))
        self.label_6.setText(_translate("dialog", "作者名称"))
        self.pushButton_7.setText(_translate("dialog", "保存作者"))
        self.label_8.setText(_translate("dialog", "页数"))
        self.pushButton_5.setText(_translate("dialog", "历史作者"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_author), _translate("dialog", "作者"))
        self.pushButton_4.setText(_translate("dialog", "选择位置"))
        self.proxyPathEdit.setPlaceholderText(_translate("dialog", "格式:ip:端口号"))
        self.isOpenAgentCheckBox.setText(_translate("dialog", "开启代理"))
        self.savePathEdit.setPlaceholderText(_translate("dialog", "下载的视频存放位置 点击右侧按钮进行选择"))
        self.authorCheckBox.setText(_translate("dialog", "文件名前添加作者"))
        self.passwordLineEdit.setPlaceholderText(_translate("dialog", "请输入密码"))
        self.label_10.setText(_translate("dialog", "密码"))
        self.accountLineEdit.setPlaceholderText(_translate("dialog", "请输入帐号"))
        self.label_5.setText(_translate("dialog", "Cookie"))
        self.cookieEdit.setPlaceholderText(_translate("dialog", "请输入cookie"))
        self.label_9.setText(_translate("dialog", "帐号"))
        self.loginButton.setText(_translate("dialog", "登录"))
        self.label_3.setText(_translate("dialog", "同时下载任务数"))
        self.button_box.setTitle(_translate("dialog", "解析下载"))
        self.pushButton.setText(_translate("dialog", "解析地址"))
        self.pushButton_8.setText(_translate("dialog", "检查状态"))
        self.batchDownloadButton.setText(_translate("dialog", "批量下载"))
        self.downloadOneButton.setText(_translate("dialog", "下载单个"))
        self.infoLabel.setText(_translate("dialog", "等待"))
import res_rc
