# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HisUrlDialogView.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 346)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setStyleSheet("QListView{\n"
"font: 12pt \"楷体\";\n"
"}")
        self.listView.setObjectName("listView")
        self.horizontalLayout.addWidget(self.listView)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton {font: 12pt \"楷体\";\n"
"border-radius:4px;\n"
"/*border: 1px solid gray;*/\n"
"/* 边框颜色 */  \n"
"border: 1px solid gray;\n"
"background-color: rgb(224, 213, 255);}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(234, 228, 255);}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid gray;\n"
"border-style:inset;\n"
"/* 使文字有一点移动 */  \n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton {font: 12pt \"楷体\";\n"
"border-radius:4px;\n"
"/*border: 1px solid gray;*/\n"
"/* 边框颜色 */  \n"
"border: 1px solid gray;\n"
"background-color: rgb(224, 213, 255);}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(234, 228, 255);}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid gray;\n"
"border-style:inset;\n"
"/* 使文字有一点移动 */  \n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("QPushButton {font: 12pt \"楷体\";\n"
"border-radius:4px;\n"
"/*border: 1px solid gray;*/\n"
"/* 边框颜色 */  \n"
"border: 1px solid gray;\n"
"background-color: rgb(224, 213, 255);}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(234, 228, 255);}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid gray;\n"
"border-style:inset;\n"
"/* 使文字有一点移动 */  \n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        spacerItem = QtWidgets.QSpacerItem(20, 120, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {font: 12pt \"楷体\";\n"
"border-radius:4px;\n"
"/*border: 1px solid gray;*/\n"
"/* 边框颜色 */  \n"
"border: 1px solid gray;\n"
"background-color: rgb(224, 213, 255);}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(234, 228, 255);}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid gray;\n"
"border-style:inset;\n"
"/* 使文字有一点移动 */  \n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {font: 12pt \"楷体\";\n"
"border-radius:4px;\n"
"/*border: 1px solid gray;*/\n"
"/* 边框颜色 */  \n"
"border: 1px solid gray;\n"
"background-color: rgb(224, 213, 255);}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(234, 228, 255);}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid gray;\n"
"border-style:inset;\n"
"/* 使文字有一点移动 */  \n"
"padding-left:3px;\n"
"padding-top:3px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)

        self.retranslateUi(Dialog)
        self.pushButton_2.clicked.connect(Dialog.ok_btn_click)
        self.pushButton.clicked.connect(Dialog.cancel_btn_click)
        self.pushButton_3.clicked.connect(Dialog.delete_row_btn_click)
        self.pushButton_4.clicked.connect(Dialog.clear_rows_btn_click)
        self.pushButton_5.clicked.connect(Dialog.save_data_to_file_btn_click)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_3.setText(_translate("Dialog", "删除"))
        self.pushButton_4.setText(_translate("Dialog", "清空"))
        self.pushButton_5.setText(_translate("Dialog", "保存"))
        self.pushButton_2.setText(_translate("Dialog", "确定"))
        self.pushButton.setText(_translate("Dialog", "取消"))
import res_rc
